name: validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

env:
  REPO_SLUG_ORIGIN: "moby/buildkit:latest"
  BUILDX_VERSION: "v0.9.1"  # leave empty to use the one available on GitHub virtual environment

jobs:
  validate:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint
          - validate-vendor
          - validate-generated-files
          - validate-shfmt
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ env.BUILDX_VERSION }}
          driver-opts: image=${{ env.REPO_SLUG_ORIGIN }}
          buildkitd-flags: --debug
      -
        name: Run
        run: |
          make ${{ matrix.target }}
